<?php
if(session_status()===PHP_SESSION_NONE)session_start();header('Content-Type: application/json; charset=utf-8');
if(empty($_SESSION['is_logged_in'])){http_response_code(401);echo json_encode(['success'=>false,'message'=>'Authentification requise'],JSON_UNESCAPED_UNICODE);exit;}
require_once __DIR__.'/../../config/database.php';$data=json_decode(file_get_contents('php://input'),true)?:$_POST;$action=$data['action']??'';$id=filter_var($data['id']??null,FILTER_VALIDATE_INT);
function orderResponse(bool $ok,string $message,array $extra=[]):void{echo json_encode(array_merge(['success'=>$ok,'message'=>$message],$extra),JSON_UNESCAPED_UNICODE);exit;}
$role=$_SESSION['user_type']??'';$permissions=['admin'=>['details','update_payment','adjust_stock','update_status'],'gestionnaire'=>['details','update_payment','adjust_stock','update_status'],'serveur'=>['details','update_status'],'cuisinier'=>['adjust_stock']];if(!in_array($action,$permissions[$role]??[],true)){http_response_code(403);orderResponse(false,'Vous n’avez pas l’autorisation d’effectuer cette action.');}
if($action==='details'&&$id){$order=fetchOne('SELECT o.*,t.number table_number,CONCAT(u.nom," ",u.postnom) client_name,u.phone client_phone FROM orders o LEFT JOIN tables t ON t.id=o.table_id LEFT JOIN users u ON u.id=o.user_id WHERE o.id=:id AND o.supprimer=0',[':id'=>$id]);if(!$order)orderResponse(false,'Commande introuvable.');$items=fetchAll('SELECT oi.*,m.nom menu_name,m.image,m.stock_quantity FROM order_items oi JOIN menus m ON m.id=oi.menu_id WHERE oi.order_id=:id AND oi.supprimer=0 ORDER BY oi.id',[':id'=>$id]);$movements=fetchAll('SELECT sm.*,m.nom menu_name FROM stock_movements sm JOIN menus m ON m.id=sm.menu_id WHERE sm.raison LIKE :reason AND sm.supprimer=0 ORDER BY sm.created_at DESC',[':reason'=>'%'.$order->order_number.'%']);orderResponse(true,'Détails chargés.',['order'=>$order,'items'=>$items,'movements'=>$movements]);}
if($action==='update_payment'&&$id){$status=$data['payment_status']??'';if(!in_array($status,['en attente','payer','partially_paid'],true))orderResponse(false,'Statut de paiement invalide.');$ok=executeQuery('UPDATE orders SET payment_status=:status,status=IF(:status="payer","payer",status) WHERE id=:id AND supprimer=0',[':status'=>$status,':id'=>$id]);orderResponse((bool)$ok,$ok?'Paiement mis à jour.':'Mise à jour impossible.');}
if($action==='adjust_stock'){$menuId=filter_var($data['menu_id']??null,FILTER_VALIDATE_INT);$qty=filter_var($data['quantity']??null,FILTER_VALIDATE_INT);$type=$data['type']??'';$reason=trim($data['raison']??'Ajustement manuel');if(!$menuId||!$qty||$qty<1||!in_array($type,['entree','sortie','ajustement','perdus'],true))orderResponse(false,'Mouvement de stock invalide.');$delta=$type==='entree'||$type==='ajustement'?$qty:-$qty;global $pdo;try{$pdo->beginTransaction();$menu=fetchOne('SELECT stock_quantity FROM menus WHERE id=:id AND supprimer=0 FOR UPDATE',[':id'=>$menuId]);if(!$menu)throw new Exception('Menu introuvable.');if($menu->stock_quantity+$delta<0)throw new Exception('Stock insuffisant.');executeQuery('UPDATE menus SET stock_quantity=stock_quantity+:delta WHERE id=:id',[':delta'=>$delta,':id'=>$menuId]);executeInsert('INSERT INTO stock_movements(menu_id,type,quantity,raison) VALUES(:menu,:type,:qty,:reason)',[':menu'=>$menuId,':type'=>$type,':qty'=>$qty,':reason'=>$reason]);$pdo->commit();orderResponse(true,'Stock mis à jour.');}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();orderResponse(false,$e->getMessage());}}
if($action==='update_status'&&$id){$status=$data['status']??'';$valid=['en attente','confirme','en preparation','servis','payer','annuler'];if(!in_array($status,$valid,true))orderResponse(false,'Statut invalide.');global $pdo;try{$pdo->beginTransaction();$order=fetchOne('SELECT * FROM orders WHERE id=:id AND supprimer=0 FOR UPDATE',[':id'=>$id]);if(!$order)throw new Exception('Commande introuvable.');$items=fetchAll('SELECT oi.menu_id,oi.quantity,m.nom,m.stock_quantity FROM order_items oi JOIN menus m ON m.id=oi.menu_id WHERE oi.order_id=:id AND oi.supprimer=0 FOR UPDATE',[':id'=>$id]);if(in_array($status,['confirme','en preparation','servis','payer'],true)&&!$order->stock_processed){foreach($items as $item){if($item->stock_quantity<$item->quantity)throw new Exception('Stock insuffisant pour '.$item->nom.'.');executeQuery('UPDATE menus SET stock_quantity=stock_quantity-:qty WHERE id=:id',[':qty'=>$item->quantity,':id'=>$item->menu_id]);executeInsert("INSERT INTO stock_movements(menu_id,type,quantity,raison) VALUES(:menu,'sortie',:qty,:reason)",[':menu'=>$item->menu_id,':qty'=>$item->quantity,':reason'=>'Commande '.$order->order_number]);}executeQuery('UPDATE orders SET stock_processed=1 WHERE id=:id',[':id'=>$id]);}if($status==='annuler'&&$order->stock_processed){foreach($items as $item){executeQuery('UPDATE menus SET stock_quantity=stock_quantity+:qty WHERE id=:id',[':qty'=>$item->quantity,':id'=>$item->menu_id]);executeInsert("INSERT INTO stock_movements(menu_id,type,quantity,raison) VALUES(:menu,'entree',:qty,:reason)",[':menu'=>$item->menu_id,':qty'=>$item->quantity,':reason'=>'Annulation '.$order->order_number]);}executeQuery('UPDATE orders SET stock_processed=0 WHERE id=:id',[':id'=>$id]);}$dates='';if($status==='confirme')$dates=',confirmed_at=COALESCE(confirmed_at,NOW())';if($status==='en preparation')$dates=',ready_at=NULL';if($status==='servis')$dates=',served_at=COALESCE(served_at,NOW())';executeQuery("UPDATE orders SET status=:status{$dates} WHERE id=:id",[':status'=>$status,':id'=>$id]);$pdo->commit();orderResponse(true,'Statut et stock mis à jour.');}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();orderResponse(false,$e->getMessage());}}
orderResponse(false,'Action non reconnue.');
