<?php
if(session_status()===PHP_SESSION_NONE)session_start();header('Content-Type: application/json; charset=utf-8');
if(empty($_SESSION['is_logged_in'])||!in_array($_SESSION['user_type']??'', ['admin','gestionnaire'],true)){http_response_code(403);echo json_encode(['success'=>false,'message'=>'Accès non autorisé'],JSON_UNESCAPED_UNICODE);exit;}
require_once __DIR__.'/../../config/database.php';$data=json_decode(file_get_contents('php://input'),true)?:$_POST;$action=$data['action']??'';
function paymentResponse(bool $ok,string $message):void{echo json_encode(['success'=>$ok,'message'=>$message],JSON_UNESCAPED_UNICODE);exit;}
function syncOrderPayment(int $orderId):void{global $pdo;$order=fetchOne('SELECT total_amount,status FROM orders WHERE id=:id AND supprimer=0',[':id'=>$orderId]);if(!$order)throw new Exception('Commande introuvable.');$paid=fetchOne("SELECT COALESCE(SUM(amount),0) total FROM payments WHERE order_id=:id AND supprimer=0 AND status='valide'",[':id'=>$orderId]);$sum=(float)($paid->total??0);$paymentStatus=$sum<=0?'en attente':($sum>=(float)$order->total_amount?'payer':'partially_paid');$orderStatus=$paymentStatus==='payer'&&$order->status!=='annuler'?'payer':$order->status;executeQuery('UPDATE orders SET payment_status=:payment,status=:status WHERE id=:id',[':payment'=>$paymentStatus,':status'=>$orderStatus,':id'=>$orderId]);}
if($action==='create'){$orderId=filter_var($data['order_id']??null,FILTER_VALIDATE_INT);$amount=filter_var($data['amount']??null,FILTER_VALIDATE_FLOAT);$method=$data['payment_method']??'especes';$reference=trim($data['reference']??'')?:null;$methods=['especes','mobile_money','carte','virement'];if(!$orderId||$amount===false||$amount<=0||!in_array($method,$methods,true))paymentResponse(false,'Données de paiement invalides.');global $pdo;try{$pdo->beginTransaction();$order=fetchOne("SELECT total_amount FROM orders WHERE id=:id AND supprimer=0 AND status<>'annuler' FOR UPDATE",[':id'=>$orderId]);if(!$order)throw new Exception('Commande introuvable ou annulée.');$paid=fetchOne("SELECT COALESCE(SUM(amount),0) total FROM payments WHERE order_id=:id AND supprimer=0 AND status='valide'",[':id'=>$orderId]);$remaining=(float)$order->total_amount-(float)$paid->total;if($amount>$remaining)throw new Exception('Le montant dépasse le solde restant de '.number_format($remaining,0,',',' ').' FC.');executeInsert('INSERT INTO payments(order_id,amount,payment_method,reference,status) VALUES(:order,:amount,:method,:reference,"valide")',[':order'=>$orderId,':amount'=>$amount,':method'=>$method,':reference'=>$reference]);syncOrderPayment($orderId);$pdo->commit();paymentResponse(true,'Paiement enregistré avec succès.');}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();paymentResponse(false,$e->getMessage());}}
if($action==='cancel'){$id=filter_var($data['id']??null,FILTER_VALIDATE_INT);if(!$id)paymentResponse(false,'Paiement invalide.');global $pdo;try{$pdo->beginTransaction();$payment=fetchOne("SELECT order_id FROM payments WHERE id=:id AND supprimer=0 AND status='valide' FOR UPDATE",[':id'=>$id]);if(!$payment)throw new Exception('Paiement introuvable ou déjà annulé.');executeQuery("UPDATE payments SET status='annule' WHERE id=:id",[':id'=>$id]);syncOrderPayment((int)$payment->order_id);$pdo->commit();paymentResponse(true,'Paiement annulé et solde recalculé.');}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();paymentResponse(false,$e->getMessage());}}
paymentResponse(false,'Action non reconnue.');
