<?php
if(session_status()===PHP_SESSION_NONE)session_start();header('Content-Type: application/json; charset=utf-8');
if(empty($_SESSION['is_logged_in'])||!in_array($_SESSION['user_type']??'', ['admin','gestionnaire'],true)){http_response_code(403);echo json_encode(['success'=>false,'message'=>'Accès non autorisé'],JSON_UNESCAPED_UNICODE);exit;}
require_once __DIR__.'/../../config/database.php';$data=json_decode(file_get_contents('php://input'),true)?:$_POST;$action=$data['action']??'';$id=filter_var($data['id']??null,FILTER_VALIDATE_INT);
function tableResponse(bool $ok,string $message):void{echo json_encode(['success'=>$ok,'message'=>$message],JSON_UNESCAPED_UNICODE);exit;}
if($action==='regenerate'&&$id){$token=bin2hex(random_bytes(16));$ok=executeQuery('UPDATE tables SET qr_code_token=:token WHERE id=:id AND supprimer=0',[':token'=>$token,':id'=>$id]);tableResponse((bool)$ok,$ok?'QR code régénéré avec succès.':'Régénération impossible.');}
if($action==='delete'&&$id){$orders=fetchOne('SELECT COUNT(*) total FROM orders WHERE table_id=:id AND supprimer=0',[':id'=>$id]);if(($orders->total??0)>0)tableResponse(false,'Cette table est liée à des commandes et ne peut pas être supprimée.');$ok=executeQuery('UPDATE tables SET supprimer=1,is_active=0 WHERE id=:id',[':id'=>$id]);tableResponse((bool)$ok,$ok?'Table supprimée avec succès.':'Suppression impossible.');}
if(!in_array($action,['create','update'],true))tableResponse(false,'Action ou données invalides.');
$number=strtoupper(trim($data['number']??''));$capacity=filter_var($data['capacity']??null,FILTER_VALIDATE_INT);$status=$data['status']??'available';$active=!empty($data['is_active'])?1:0;$statuses=['available','occupied','reserved','cleaning'];
if($number===''||!$capacity||$capacity<1)tableResponse(false,'Numéro et capacité valide sont requis.');if(!in_array($status,$statuses,true))tableResponse(false,'Statut invalide.');if(fetchOne('SELECT id FROM tables WHERE number=:number AND supprimer=0 AND id<>:id',[':number'=>$number,':id'=>$id?:0]))tableResponse(false,'Ce numéro de table existe déjà.');
if($action==='create'){$token=bin2hex(random_bytes(16));$new=executeInsert('INSERT INTO tables(number,capacity,qr_code_token,status,is_active) VALUES(:number,:capacity,:token,:status,:active)',[':number'=>$number,':capacity'=>$capacity,':token'=>$token,':status'=>$status,':active'=>$active]);tableResponse((bool)$new,$new?'Table créée avec succès.':'Création impossible.');}
if(!$id)tableResponse(false,'Table invalide.');$ok=executeQuery('UPDATE tables SET number=:number,capacity=:capacity,status=:status,is_active=:active WHERE id=:id AND supprimer=0',[':number'=>$number,':capacity'=>$capacity,':status'=>$status,':active'=>$active,':id'=>$id]);tableResponse((bool)$ok,$ok?'Table modifiée avec succès.':'Modification impossible.');
